# Generated by Django 5.2.3 on 2025-08-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location_for_apartment',
            new_name='LocationForApartment',
        ),
    ]
